#!/bin/bash

java -jar /home/benji/Research_Programs/Trimmomatic-0.35/trimmomatic-0.35.jar PE -threads 6 -phred33 -basein *R1_001.fastq.gz -baseout VMM.fq ILLUMINACLIP:/home/benji/Research_Programs/Trimmomatic-0.35/adapters/NexteraPE-PE.fa:2:30:10 HEADCROP:10 LEADING:20 TRAILING:20 SLIDINGWINDOW:5:20 CROP:70 MINLEN:25

bowtie2 --very-sensitive --un-conc trim.fq -x /home/benji/Dropbox/Rlv3841_Reference_Files/RLV_rRNA/RLVRRNA -1 *1P.fq -2 *2P.fq -S /tmp/tmp.sam

bowtie -n 2 -l 25 -I 1 -X 250 -p 6 -m 5 -S /home/benji/Dropbox/Rlv3841_Reference_Files/bowtie/RLV3841 -1 *.2.fq -2 *.1.fq output.sam

samtools view -S -b output.sam > output.bam

samtools sort output.bam output.sort

samtools index output.sort.bam output.sort.bai

exit
