#!/bin/bash

fastqc *L001_R1_001.fastq.gz *L001_R2_001.fastq.gz

java -jar /home/benji/Research_Programs/Trimmomatic-0.35/trimmomatic-0.35.jar PE -threads 6 -phred33 -basein *R1_001.fastq.gz -baseout TY.fq ILLUMINACLIP:/home/benji/Research_Programs/Trimmomatic-0.35/adapters/NexteraPE-PE.fa:2:30:10 HEADCROP:10 LEADING:20 TRAILING:20 SLIDINGWINDOW:5:20 CROP:70 MINLEN:25

fastqc *1P.fq *2P.fq

bowtie2 --very-sensitive --un-conc 24D_Clean.fq -x /home/benji/Dropbox/Rlv3841_Reference_Files/RLV_rRNA/RLVRRNA -1 *1P.fq -2 *2P.fq -S /tmp/tmp.sam

fastqc *.1.fq *.2.fq

rsem-calculate-expression -p 6 --calc-pme --calc-ci --estimate-rspd --strand-specific --paired-end *.2.fq *.1.fq /home/benji/Dropbox/Rlv3841_Reference_Files/RLV3841 RLV3841_TY_R2R1_Strand_Specific
